storePassword=Ram&siva112
keyPassword=Ram&siva112
keyAlias=nutella
storeFile=/Users/ramprasadsreerama/nutella.jks

# storePassword=gocarclean@123
# keyPassword=gocarclean@123
# keyAlias=go-car-clean-provider
# storeFile=gocarclean-provider-keystore.jks
